#!/usr/bin/env python3
"""Emit paper/tables/*.tex from paper/FACTS.json and nothing else.

booktabs, no vertical rules, no colour, sized for the NeurIPS 5.5in text
column. Every cell is a FACTS lookup; the generator has no literals of its own
beyond column headers and units.

    python paper/make_tables.py
"""

from __future__ import annotations

import json
from pathlib import Path

PAPER = Path(__file__).resolve().parent
TABDIR = PAPER / "tables"
FACTS_PATH = PAPER / "FACTS.json"

MODELS = [("llama", "Llama-3.1-8B"),
          ("mistral", "Mistral-7B-v0.3"),
          ("qwen", "Qwen2.5-7B")]
OPPS = [("allc", "ALLC"), ("tft", "TFT")]

_F: dict = {}
WRITTEN: list[tuple[str, int]] = []


def v(key):
    if key not in _F:
        raise KeyError(f"FACTS.json has no key {key!r}")
    return _F[key]["value"]


def has(key):
    return key in _F


# ---------------------------------------------------------------------------
# formatting
# ---------------------------------------------------------------------------

def esc(s: str) -> str:
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("&", r"\&"),
                 ("%", r"\%"), ("#", r"\#")):
        s = s.replace(a, b)
    return s


def num(x, nd=3):
    if x is None:
        return "--"
    return f"{x:.{nd}f}"


def ci(d, lo, hi, nd=3):
    if d is None:
        return "--"
    return f"{d:+.{nd}f} [{lo:+.{nd}f}, {hi:+.{nd}f}]"


def pval(p):
    if p is None:
        return "--"
    if p <= 1e-4:
        return r"$<$0.0001"
    return f"{p:.4f}".rstrip("0").rstrip(".")


def pfmt(p):
    """$p<0.0001$ or $p=0.0612$ - never the ugly '$p$=$<$0.0001'."""
    if p is None:
        return "$p$ n/a"
    if p <= 1e-4:
        return "$p<0.0001$"
    return "$p=" + f"{p:.4f}".rstrip("0").rstrip(".") + "$"


def write(name: str, body: str) -> None:
    TABDIR.mkdir(parents=True, exist_ok=True)
    path = TABDIR / f"{name}.tex"
    header = ("% generated by paper/make_tables.py from paper/FACTS.json\n"
              "% do not edit by hand; every number is traceable through "
              "FACTS.json to a file or a query\n")
    path.write_text(header + body, encoding="utf-8")
    WRITTEN.append((path.name, path.stat().st_size))
    print(f"    wrote {path.name}")


def table(name, caption, colspec, header_rows, body_rows, note=None,
          small=True, width=None):
    L = [r"\begin{table}[t]", r"\centering", r"\caption{" + caption + "}",
         r"\label{tab:" + name.split("_", 1)[1] + "}"]
    if small:
        L.append(r"\footnotesize")
    L.append(r"\begin{tabular}{" + colspec + "}")
    L.append(r"\toprule")
    for i, hr in enumerate(header_rows):
        L.append(hr)
    L.append(r"\midrule")
    L.extend(body_rows)
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    if note:
        L.append(r"\vspace{2pt}")
        L.append(r"\begin{minipage}{\linewidth}\scriptsize " + note +
                 r"\end{minipage}")
    L.append(r"\end{table}")
    write(name, "\n".join(L) + "\n")


# ===========================================================================
# tab1 - the arm ladder
# ===========================================================================

LADDER = [("1", "no [STATE] block at all"),
          ("3b", "token-matched block with no state"),
          ("3", "the true state"),
          ("3c", "another episode's state (donor)"),
          ("3s", "true state, own score offset"),
          ("3m", "true state, opponent's last move flipped")]

TAB1_GROUP = "exp6_llama_sem_logit"


def tab1_arms():
    src = v("arm_ladder.source")
    rows = []
    for arm, desc in LADDER:
        block = v(f"arm_ladder.{arm}")["state_block"]
        line = (r"\texttt{" + esc(block.split("\n")[1]) + "}"
                if block else r"\emph{no block rendered}")
        cprk = f"cpr.{TAB1_GROUP}.{arm}|pooled"
        cpr = num(v(cprk)["cpr_all_or_nothing"]) if has(cprk) else "--"
        fals = []
        for ok, ol in OPPS:
            k = f"falsification.{TAB1_GROUP}.{arm}|{ok}"
            fals.append(num(v(k)["rate"], 3) if has(k) else "--")
        rows.append(" & ".join([
            r"\texttt{" + arm + "}", desc, line, cpr,
            fals[0], fals[1]]) + r" \\")
    tok = src["parity_target_tokens"]
    table(
        "tab1_arms",
        "The arm ladder. Every block is padded to exactly "
        f"{tok} tokens under the {esc(src['model_id'])} tokenizer, so the arms "
        "differ in content and in nothing else. Sample line is taken verbatim "
        f"from a rendered prompt in \\texttt{{{esc(src['database'])}}}.",
        "llll rr",
        [r"\multicolumn{4}{c}{} & \multicolumn{2}{c}{falsification rate} \\",
         r"\cmidrule(l){5-6}",
         r"arm & what the block asserts & first content line & CPR & "
         r"ALLC & TFT \\"],
        rows,
        note="CPR is the all-or-nothing comprehension probe rate over both "
             "opponents, turn 0 excluded. Falsification rate is the fraction "
             "of turns on which the block's stated opponent-last move "
             "contradicts the true one; it is undefined (--) for arms that "
             "assert nothing about that field.")


# ===========================================================================
# tab2 - the pre-registered test
# ===========================================================================

EXP7_GROUPS = ["exp7_llama_abs_logit", "exp7_llama_absnohist_logit",
               "exp7_llama_nohist_logit", "exp7_llama_swap_logit",
               "exp7_mistral_nohist_logit", "exp7_qwen_abs_logit",
               "exp7_qwen_absnohist_logit", "exp7_qwen_nohist_logit",
               "exp7_qwen_swap_logit"]


def tab2_registered_test():
    rows = []
    for g in EXP7_GROUPS:
        ident = v(f"identity.{g}")
        for ok, ol in OPPS:
            q = v(f"contrast.{g}.ATE_true|{ok}")["quotable"]
            rows.append(" & ".join([
                r"\texttt{" + esc(g.replace("exp7_", "").replace("_logit", ""))
                + "}" if ok == "allc" else "",
                ident["model"] if ok == "allc" else "",
                ol,
                ci(q["diff"], q["lo"], q["hi"]),
                pval(q["p"]),
                "yes" if q["sig"] else "no"]) + r" \\")
        rows.append(r"\addlinespace[1pt]")
    m = v("multiplicity.exp7")
    table(
        "tab2_registered_test",
        "The pre-registered test. ATE\\textsubscript{true} is "
        "$P(\\text{defect}\\mid\\text{arm }3)-P(\\text{defect}\\mid"
        "\\text{arm }3b)$: the effect of the block's \\emph{content}, holding "
        "its token count and density fixed. Turn 0 excluded; 95\\% intervals "
        "are percentile bootstraps clustered on the episode.",
        "lll ccc",
        [r"group & model & opp. & ATE$_{\text{true}}$ [95\% CI] & $p$ & "
         r"sig. \\"],
        rows,
        note=f"Family of {m['family_size']} contrasts across all exp7 groups: "
             f"{m['raw_significant']} significant at raw $p<0.05$, "
             f"{m['holm_significant']} surviving Holm, "
             f"{m['bh_significant']} surviving Benjamini--Hochberg.")


# ===========================================================================
# tab3 - which field carries the effect
# ===========================================================================

TAB3_GROUPS = [f"exp6_{m}_sem_logit" for m, _ in MODELS]
FIELD_CONTRASTS = [("content_move", r"content\_move (3--3m)"),
                   ("content_score", r"content\_score (3--3s)"),
                   ("content_donor", r"content\_donor (3--3c)"),
                   ("ATE_true", r"ATE\_true (3--3b)"),
                   ("perturbation", r"perturbation (3b--1)")]


def tab3_field_contrasts():
    rows = []
    for g, (mk, mlabel) in zip(TAB3_GROUPS, MODELS):
        first = True
        for key, label in FIELD_CONTRASTS:
            cells = []
            for ok, _ in OPPS:
                k = f"contrast.{g}.{key}|{ok}"
                if not has(k):
                    cells.append("--")
                    continue
                q = v(k)["quotable"]
                cells.append(ci(q["diff"], q["lo"], q["hi"]))
            rows.append(" & ".join(
                [mlabel if first else "", label] + cells) + r" \\")
            first = False
        rows.append(r"\addlinespace[1pt]")
    table(
        "tab3_field_contrasts",
        "Which field of the state block carries the behavioural effect. Each "
        "entry is a difference in $P(\\text{defect})$ with a 95\\% "
        "episode-clustered bootstrap interval, turn 0 excluded. Arms 3m and 3c "
        "are byte-identical to arm 3 at turn 0, so those rows would be diluted "
        "by a turn that carries no manipulation.",
        "ll cc",
        [r"model & contrast & vs ALLC & vs TFT \\"],
        rows,
        note="Read against Table~\\ref{tab:arms}: arm 3s is answered back "
             "correctly on every probe and yet moves behaviour by less than a "
             "point, which is the dissociation the paper is about.")


# ===========================================================================
# tab4 - history deprivation
# ===========================================================================

FIELDS = [("own_score", "own score"),
          ("opponent_last", "opponent's last move"),
          ("rounds_played", "rounds played")]


def tab4_deprivation():
    rows = []
    for mk, mlabel in MODELS:
        for gtpl, cond in [("exp6_{}_sem_logit", "with history"),
                           ("exp7_{}_nohist_logit", "no history")]:
            g = gtpl.format(mk)
            c = v(f"cpr.{g}.1|pooled")
            b = v(f"probe_baseline.{g}.1|pooled")
            rows.append(" & ".join([
                mlabel if cond == "with history" else "",
                cond,
                num(c["own_score"]), num(c["opponent_last"]),
                num(c["rounds_played"]),
                num(c["cpr_all_or_nothing"]),
                num(b["constant_answer_accuracy"], 2)]) + r" \\")
        rows.append(r"\addlinespace[1pt]")
    table(
        "tab4_deprivation",
        "Arm 1 comprehension probes with and without the move-by-move "
        "history. With history, recall of the opponent's last move is close to "
        "ceiling and only the arithmetic probe fails; removing the history "
        "collapses every field, including the counting probe, which requires "
        "no reasoning at all.",
        "ll ccc cc",
        [r"\multicolumn{2}{c}{} & \multicolumn{3}{c}{per-field accuracy} & "
         r"& \\",
         r"\cmidrule(lr){3-5}",
         r"model & condition & own score & opp.\ last & rounds & CPR & "
         r"const.\ floor \\"],
        rows,
        note="Turn 0 excluded throughout. CPR is all-or-nothing over the three "
             "probes. The constant floor is the score a model would get on the "
             "binary opponent-last probe by ignoring the prompt and always "
             "answering the majority label, so any value at or below it is "
             "uninformative about reading.")


# ===========================================================================
# tab5 - the label-swap rescore
# ===========================================================================

SWAP_GROUPS = ["exp3_llama_swap", "exp3_mistral_swap", "exp3_qwen_swap",
               "exp7_llama_swap_logit", "exp7_qwen_swap_logit"]
SWAP_ARMS = ["1", "3", "3b", "3c", "3d", "3m", "3s"]


def tab5_swap_rescore():
    rows = []
    for g in SWAP_GROUPS:
        cont = v(f"swap_contingency.{g}")
        arms = [a for a in SWAP_ARMS if has(f"swap_rescore.{g}.{a}|allc")]
        first = True
        for a in arms:
            cells = []
            for ok, _ in OPPS:
                k = f"swap_rescore.{g}.{a}|{ok}"
                if not has(k):
                    cells += ["--", "--"]
                    continue
                r = v(k)
                cells += [num(r["cpr_as_run"]), num(r["cpr_rescored"])]
            rows.append(" & ".join(
                [r"\texttt{" + esc(g) + "}" if first else "",
                 num(cont["frac_inverted"]) if first else "",
                 r"\texttt{" + a + "}"] + cells) + r" \\")
            first = False
        rows.append(r"\addlinespace[1pt]")
    table(
        "tab5_swap_rescore",
        "The label-swap groups were graded in the wrong label space. Column "
        "``inv.'' is the fraction of opponent-last probe answers that are an "
        "exact inversion of the truth, computed before any correction; it is "
        "the evidence that licenses the rescore. Rescoring inverts only the "
        "opponent-last answer and touches no behavioural datum.",
        "lll cc cc",
        [r"\multicolumn{3}{c}{} & \multicolumn{2}{c}{vs ALLC} & "
         r"\multicolumn{2}{c}{vs TFT} \\",
         r"\cmidrule(lr){4-5}\cmidrule(l){6-7}",
         r"group & inv. & arm & as run & rescored & as run & rescored \\"],
        rows,
        note="Pre-registered comprehension gate is 0.85. Arm 3 is the only arm "
             "that displays the true state, so it is the only arm the gate "
             "applies to; arms 3b, 3c, 3d, 3m and 3s assert something false or "
             "nothing at all and a low CPR there is not a failure.")


# ===========================================================================
# tab6 - multiplicity
# ===========================================================================

def tab6_multiplicity():
    rows = []
    for fam, label in [("exp2-exp6", "exp2--exp6 (34 databases)"),
                       ("exp7", "exp7 (9 databases)")]:
        m = v(f"multiplicity.{fam}")
        rows.append(" & ".join([
            label, str(m["family_size"]), str(m["raw_significant"]),
            str(m["holm_significant"]), str(m["bh_significant"]),
            str(m["n_floor_effects"])]) + r" \\")
    het = []
    for fam in ("exp2-exp6", "exp7"):
        for stratum in ("all|allc", "all|tft"):
            k = f"heterogeneity.{fam}.{stratum}"
            if not has(k):
                continue
            h = v(k)
            het.append(" & ".join([
                fam.replace("_", "--"), stratum.replace("|", " / "),
                str(h["k_groups"]), num(h["joint_Q"], 4), pval(h["p"]),
                num(h["spread"], 3)]) + r" \\")
    table(
        "tab6_multiplicity",
        "Multiplicity and heterogeneity. The contrast family is five contrasts "
        "$\\times$ two opponents $\\times$ every group in the stratum. Holm "
        "controls the family-wise error rate, Benjamini--Hochberg the false "
        "discovery rate; both are applied to the turn-0-excluded $p$-values.",
        "l ccccc",
        [r"family & size & raw $p<0.05$ & Holm & BH & floor effects \\"],
        rows,
        note="Floor effects are contrasts whose estimate and interval are both "
             "within $10^{-3}$ of zero, i.e.\\ cells where the model never "
             "varies its action; they inflate the survivor count without "
             "carrying evidence and are counted separately. Joint "
             "heterogeneity across groups: " +
             "; ".join(
                 f"{fam} {stratum.replace('|', '/')} $Q="
                 f"{num(v(f'heterogeneity.{fam}.{stratum}')['joint_Q'], 3)}$, "
                 f"{pfmt(v(f'heterogeneity.{fam}.{stratum}')['p'])}, "
                 f"spread {num(v(f'heterogeneity.{fam}.{stratum}')['spread'])}"
                 for fam in ("exp2-exp6", "exp7")
                 for stratum in ("all|allc", "all|tft")
                 if has(f"heterogeneity.{fam}.{stratum}")) + ".")


TABLES = [tab1_arms, tab2_registered_test, tab3_field_contrasts,
          tab4_deprivation, tab5_swap_rescore, tab6_multiplicity]


def main() -> int:
    global _F
    if not FACTS_PATH.exists():
        raise SystemExit("paper/FACTS.json missing - run paper/extract_facts.py")
    _F = json.loads(FACTS_PATH.read_text(encoding="utf-8"))["facts"]
    print(f"\ntables from {FACTS_PATH.name} ({len(_F)} facts)")
    failed = []
    for fn in TABLES:
        try:
            fn()
        except Exception as exc:                       # noqa: BLE001
            failed.append((fn.__name__, f"{type(exc).__name__}: {exc}"))
            print(f"    COULD NOT BUILD {fn.__name__}: {exc}")
    print("\ntable inventory")
    for n, s in WRITTEN:
        print(f"    {n:<28}{s:>7} bytes")
    for n, why in failed:
        print(f"    NOT BUILT {n}: {why}")
    return len(failed)


if __name__ == "__main__":
    raise SystemExit(main())
